# Generated by Django 4.2.20 on 2025-04-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_end_date_project_start_date_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
