# Generated by Django 4.2.20 on 2025-04-25 07:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, unique=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
