# Generated by Django 4.2.20 on 2025-04-25 11:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_image_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_card',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
