# Generated by Django 4.2.20 on 2025-04-25 11:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_image_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_card',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_card'),
        ),
    ]
