# Generated by Django 4.2.20 on 2025-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_project_image_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
